link:
  camunda:
    workerId: camunda-test-worker
    # 一次fetch最大任务数量
    fetchMaxTaskNum: 1
    # 一次fetch任务锁定时间（锁定期间再fetch是fetch不到的）
    lockTime: 600000
    # fetch的topicName
    topic:
      checkCard: check-card
      chargeCard: charge-Card
    tenantId: CamundaTest
    camundaRestUrl: http://localhost:8080/engine-rest
    username: demo
    password: demo
server:
  port: 9050



camunda.bpm:
  admin-user:
    id: demo
    password: demo
  database:
    type: h2
    schema-update: true
  deployment-resource-pattern:
    - classpath*:camunda/*.bpmn
  auto-deployment-enabled: true